import { SkillItem, SportType } from '../types/scout';

export const INITIAL_SKILLS: SkillItem[] = [
  // Badminton
  {
    id: 'bad-smash',
    sport: 'badminton',
    name: 'Smash',
    nameTh: 'ตบ / สแมช',
    category: 'attack',
    aliases: ['ตบ', 'ฟาด', 'สแมช', 'smash', 'jump smash'],
    enabled: true,
    isCore: true,
    count: 14,
  },
  {
    id: 'bad-net-kill',
    sport: 'badminton',
    name: 'Net Kill',
    nameTh: 'ซ้ำหน้าเน็ต',
    category: 'attack',
    aliases: ['เน็ตกิล', 'ซ้ำหน้าเน็ต', 'เคาะหน้าเน็ต', 'kill'],
    enabled: true,
    isCore: true,
    count: 6,
  },
  {
    id: 'bad-drop',
    sport: 'badminton',
    name: 'Drop',
    nameTh: 'หยอด / ตัดหยอด',
    category: 'attack',
    aliases: ['หยอด', 'ลูกหยอด', 'ตีหยอด', 'ตัดหยอด', 'drop', 'drop shot'],
    enabled: true,
    isCore: true,
    count: 18,
  },
  {
    id: 'bad-clear',
    sport: 'badminton',
    name: 'Clear',
    nameTh: 'เคลียร์ / โยนหลัง',
    category: 'transition',
    aliases: ['เคลียร์', 'โยน', 'โยนหลัง', 'เซฟ', 'clear'],
    enabled: true,
    isCore: true,
    count: 22,
  },
  {
    id: 'bad-drive',
    sport: 'badminton',
    name: 'Drive',
    nameTh: 'ดาด / ไดรฟ์',
    category: 'attack',
    aliases: ['ดาด', 'ไดรฟ์', 'ไดร์ฟ', 'drive'],
    enabled: true,
    isCore: true,
    count: 9,
  },
  {
    id: 'bad-lift',
    sport: 'badminton',
    name: 'Lift',
    nameTh: 'ยก / งัด',
    category: 'defense',
    aliases: ['ยก', 'งัด', 'ยกหลัง', 'lift'],
    enabled: true,
    isCore: true,
    count: 15,
  },
  {
    id: 'bad-net-shot',
    sport: 'badminton',
    name: 'Net Shot',
    nameTh: 'วางหน้าเน็ต / ปั่นเน็ต',
    category: 'transition',
    aliases: ['ปั่นเน็ต', 'เล่นเน็ต', 'วางหน้าเน็ต', 'net shot', 'tumbling net'],
    enabled: true,
    isCore: true,
    count: 11,
  },
  {
    id: 'bad-block',
    sport: 'badminton',
    name: 'Block',
    nameTh: 'บล็อก / ดักหน้า',
    category: 'defense',
    aliases: ['บล็อก', 'ดัก', 'ดักหน้าเน็ต', 'block'],
    enabled: true,
    isCore: true,
    count: 4,
  },

  // Volleyball
  {
    id: 'vb-serve',
    sport: 'volleyball',
    name: 'Serve',
    nameTh: 'เสิร์ฟ',
    category: 'serve',
    aliases: ['เสิร์ฟ', 'เสิร์ฟเอซ', 'serve', 'jump serve'],
    enabled: true,
    isCore: true,
    count: 28,
  },
  {
    id: 'vb-reception',
    sport: 'volleyball',
    name: 'Reception',
    nameTh: 'รับบอลแรก',
    category: 'defense',
    aliases: ['รับบอลแรก', 'รับเสิร์ฟ', 'reception', 'pass'],
    enabled: true,
    isCore: true,
    count: 26,
  },
  {
    id: 'vb-set',
    sport: 'volleyball',
    name: 'Set',
    nameTh: 'เซ็ตบอล',
    category: 'transition',
    aliases: ['เซ็ต', 'จ่ายบอล', 'ยกบอล', 'set'],
    enabled: true,
    isCore: true,
    count: 32,
  },
  {
    id: 'vb-attack',
    sport: 'volleyball',
    name: 'Attack',
    nameTh: 'ตบ / โจมตี',
    category: 'attack',
    aliases: ['ตบ', 'สไปค์', 'ตีหัวเสา', 'attack', 'spike'],
    enabled: true,
    isCore: true,
    count: 35,
  },
  {
    id: 'vb-block',
    sport: 'volleyball',
    name: 'Block',
    nameTh: 'บล็อก',
    category: 'defense',
    aliases: ['บล็อก', 'คิลบล็อก', 'block', 'kill block'],
    enabled: true,
    isCore: true,
    count: 14,
  },
  {
    id: 'vb-dig',
    sport: 'volleyball',
    name: 'Dig',
    nameTh: 'รับตบ / ขุด',
    category: 'defense',
    aliases: ['ขุด', 'รับตบ', 'ดีก', 'dig'],
    enabled: true,
    isCore: true,
    count: 19,
  },
  {
    id: 'vb-free-ball',
    sport: 'volleyball',
    name: 'Free Ball',
    nameTh: 'ฟรีบอล',
    category: 'transition',
    aliases: ['ฟรีบอล', 'ปล่อยบอล', 'free ball'],
    enabled: true,
    isCore: true,
    count: 8,
  },
  {
    id: 'vb-cover',
    sport: 'volleyball',
    name: 'Cover',
    nameTh: 'รองบอล',
    category: 'defense',
    aliases: ['รองบอล', 'โคฟเวอร์', 'cover'],
    enabled: true,
    isCore: true,
    count: 7,
  },
];
