import React,{useState,useEffect} from 'react';
import {useScout} from '../../stores/ScoutContext';
import {useLocale} from '../../i18n/LocaleContext';
import {audioDeviceManager,DiscoveredAudioDevice} from '../../services/speech/AudioDeviceManager';
export function ConnectionPanel(){
 const {language}=useLocale();const text=(th:string,en:string)=>language==='th'?th:en;
 const {settings,updateSettings,apiStatus,refreshApiStatus}=useScout();
 const [apiKey,setApiKey]=useState('');const [deepgramKey,setDeepgramKey]=useState('');
 const [devices,setDevices]=useState<DiscoveredAudioDevice[]>([]);const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const [verified,setVerified]=useState(false);
 useEffect(()=>{void audioDeviceManager.refreshDevices().then(setDevices);return audioDeviceManager.onDeviceChange(setDevices);},[]);
 const discover=async()=>{setBusy(true);try{const result=await audioDeviceManager.requestPermissionAndDiscover();setDevices(result.devices);setMessage(result.granted?text('อนุญาตไมโครโฟนแล้ว เลือกอุปกรณ์ที่ต้องการ','Microphone permission granted. Select your device.'):result.error||text('ไม่สามารถเปิดไมโครโฟน','Microphone unavailable'));}finally{setBusy(false);}};
 const verify=async()=>{setBusy(true);setMessage('');try{const r=await fetch('/api/verify-provider',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});const data=await r.json();if(!r.ok||!data.success)throw Error(data.error);setVerified(true);setMessage(text(`เชื่อมต่อ ${data.model} สำเร็จ`,`${data.model} connected successfully`));await refreshApiStatus();}catch(e:any){setMessage(e.message||text('ตรวจสอบบริการไม่สำเร็จ','Service verification failed'));}finally{setBusy(false);}};
 const saveKey=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setMessage('');try{const r=await fetch('/api/provider-key',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({apiKey:apiKey.trim()})});const data=await r.json();if(!r.ok||!data.success)throw Error(data.error||text('บันทึกคีย์ไม่สำเร็จ','Key save failed'));setApiKey('');setVerified(true);await refreshApiStatus();setMessage(text('ทดสอบสำเร็จและบันทึกคีย์แล้ว พร้อมใช้ Gemini','Key verified and saved. Gemini is ready.'));}catch(e:any){setVerified(false);setMessage(e.message||text('บันทึกคีย์ไม่สำเร็จ','Key save failed'));}finally{setBusy(false);}};
 const saveDeepgram=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setMessage('');try{const r=await fetch('/api/deepgram-key',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({apiKey:deepgramKey.trim()})});const data=await r.json();if(!r.ok||!data.success)throw Error(data.error);setDeepgramKey('');updateSettings({transcriptionMode:'deepgram',captureMode:'continuous'});await refreshApiStatus();setMessage(text('บันทึก Deepgram แล้ว ทดสอบสิทธิ์โทเคนสำเร็จ ยังต้องทดสอบถอดเสียงจริง','Deepgram saved; token permissions verified. Live audio still requires testing.'));}catch(e:any){setMessage(e.message||'Deepgram unavailable');}finally{setBusy(false);}};
 return <section className="rounded-2xl border border-white/10 bg-[#13161c] p-4 space-y-4 text-sm">
 <div className="rounded-xl border border-sky-400/30 p-3 space-y-3"><h3 className="font-bold">{text('Deepgram · ฟังต่อเนื่องทั้งเกม','Deepgram · continuous match scouting')}</h3><p>{apiStatus.hasDeepgramKey?text('ตั้งค่าคีย์แล้ว · ยังไม่ยืนยันผลทดสอบเสียงจริง','Key configured · live audio not yet verified'):text('ยังไม่มีคีย์ Deepgram · ใช้ Gemini Key แทนไม่ได้','Deepgram key not configured · Gemini keys cannot be used here')}</p><form onSubmit={saveDeepgram} className="space-y-2"><label htmlFor="deepgram-key">Deepgram API Key</label><input id="deepgram-key" type="password" autoComplete="off" autoCapitalize="none" spellCheck={false} value={deepgramKey} onChange={e=>setDeepgramKey(e.target.value)} className="w-full rounded-lg bg-[#0f1217] border border-white/15 p-3"/><button disabled={busy||!deepgramKey.trim()} className="rounded-lg bg-sky-700 px-4 py-2 disabled:opacity-40">{text('ตรวจสอบและบันทึก Deepgram','Verify and save Deepgram')}</button></form><a href="https://console.deepgram.com/" target="_blank" rel="noreferrer" className="text-sky-300 underline">{text('สร้างคีย์ที่ Deepgram Console','Create a key in Deepgram Console')}</a><p className="text-gray-400">{text('API Keys → Create Key → Advanced → Member ต้องมีเครดิตสำหรับถอดเสียง คีย์หลักเก็บเข้ารหัสบนเซิร์ฟเวอร์ เบราว์เซอร์รับเฉพาะโทเคนชั่วคราว','API Keys → Create Key → Advanced → Member. Transcription requires credits. The API key is encrypted on the server; only temporary tokens reach the browser.')}</p></div>
 <h3 className="font-bold">{text('ไมโครโฟนและบริการถอดเสียง','Microphone and transcription services')}</h3>
 <button onClick={discover} disabled={busy} className="rounded-lg bg-sky-700 px-4 py-2">{text('อนุญาตและค้นหาไมโครโฟน','Allow and discover microphones')}</button>
 <label className="block">{text('ไมโครโฟน','Microphone')}<select className="w-full mt-1 rounded-lg bg-[#0f1217] p-3" value={settings.inputDeviceId||'default'} onChange={e=>{const d=devices.find(d=>d.deviceId===e.target.value);updateSettings({inputDeviceId:e.target.value,inputDevice:d?.label||'Default Microphone'});}}><option value="default">{text('ไมโครโฟนเริ่มต้นของอุปกรณ์','Device default microphone')}</option>{devices.filter(d=>d.deviceId!=='default').map((d,i)=><option key={d.deviceId} value={d.deviceId}>{d.label||text(`ไมโครโฟน ${i+1}`,`Microphone ${i+1}`)}</option>)}</select></label>
 <label className="block">{text('วิธีถอดเสียง','Transcription method')}<select className="w-full mt-1 rounded-lg bg-[#0f1217] p-3" value={settings.transcriptionMode||'auto'} onChange={e=>updateSettings({transcriptionMode:e.target.value as 'auto'|'browser'|'server'|'deepgram'})}><option value="deepgram">{text('Deepgram: ถอดเสียงสดต่อเนื่อง (ต้องตั้งค่าคีย์)','Deepgram: continuous live transcription (key required)')}</option><option value="auto">{text('อัตโนมัติ: Deepgram หากตั้งค่าแล้ว สำหรับฟังต่อเนื่อง','Auto: Deepgram when configured for continuous scouting')}</option><option value="browser">{text('เบราว์เซอร์: ไม่ต้องมี API Key','Browser: no app API key')}</option><option value="server">{text('Gemini: ถอดเสียงจากเสียงที่บันทึกจริง','Gemini: transcribe recorded audio')}</option></select></label>
 <p className="text-gray-400">{text('โหมดอัตโนมัติใช้ข้อความสุดท้ายจากเบราว์เซอร์ก่อน หากไม่ได้ข้อความจะส่งเสียงให้ Gemini หลังหยุดอัด การเลือกไมค์มีผลกับเสียงบันทึก Gemini แต่ระบบรู้จำเสียงของเบราว์เซอร์อาจใช้ไมค์ตามการตั้งค่าเครื่อง','Auto uses final browser recognition text first; Gemini transcribes recorded audio only if no final text is available. Device selection controls recorded audio; browser recognition may use the OS-selected microphone.')}</p>
 <div className="border-t border-white/10 pt-3 space-y-2"><p>{text('สถานะ API: ','API status: ')}{apiStatus.status==='checking'?text('กำลังตรวจสอบ','Checking'):apiStatus.status==='unavailable'?text('เชื่อมต่อเซิร์ฟเวอร์ไม่สำเร็จ','Server unavailable'):apiStatus.hasApiKey?verified?text('ทดสอบเชื่อมต่อสำเร็จ','Connection verified'):text('ตั้งค่าคีย์แล้ว ยังไม่ได้ทดสอบผู้ให้บริการ','Key configured; provider not tested'):text('ยังไม่มีคีย์ ใช้ถอดเสียงเบราว์เซอร์ได้หากรองรับ','No key; browser recognition remains available when supported')}</p>
 <div className="flex flex-wrap gap-2"><button disabled={busy} className="rounded-lg border border-white/15 px-3 py-2" onClick={()=>{setVerified(false);void refreshApiStatus();}}>{text('ตรวจสอบสถานะใหม่','Refresh status')}</button><button disabled={busy||!apiStatus.hasApiKey} className="rounded-lg border border-white/15 px-3 py-2 disabled:opacity-40" onClick={verify}>{text('ทดสอบเชื่อมต่อ Gemini','Test Gemini connection')}</button></div>
 <form onSubmit={saveKey} className="space-y-2"><label className="block" htmlFor="gemini-api-key">{text('Gemini API Key (ใส่เพื่อเพิ่มหรือเปลี่ยนคีย์)','Gemini API Key (add or replace)')}</label><input id="gemini-api-key" type="password" autoComplete="off" spellCheck={false} autoCapitalize="none" value={apiKey} onChange={e=>setApiKey(e.target.value)} placeholder={text('วาง API Key ที่นี่','Paste API key here')} className="w-full rounded-lg bg-[#0f1217] border border-white/15 p-3"/><button type="submit" disabled={busy||!apiKey.trim()} className="rounded-lg bg-sky-700 px-4 py-2 disabled:opacity-40">{busy?text('กำลังตรวจสอบ…','Checking…'):text('ทดสอบและบันทึกคีย์','Test and save key')}</button><p className="text-gray-400">{text('คีย์ถูกเข้ารหัสและบันทึกฝั่งเซิร์ฟเวอร์ เฉพาะเจ้าของเว็บเปลี่ยนได้ ระบบจะไม่ส่งคีย์เดิมกลับมาและไม่เก็บในเบราว์เซอร์','The key is encrypted on the server. Only the site owner can change it; the stored key is never returned or saved in browser storage.')}</p></form>
 {!apiStatus.hasApiKey&&<div className="bg-[#0f1217] p-3 rounded-lg space-y-2"><p>{text('เปิดทุกฟังก์ชัน AI ด้วย Gemini API Key เพียงคีย์เดียว: ถอดเสียง แยกเหตุการณ์ และสรุปการแข่งขัน','One Gemini API key enables audio transcription, event interpretation, and AI match summaries.')}</p><a href="https://aistudio.google.com/apikey" target="_blank" rel="noreferrer" className="text-sky-300 underline">{text('สร้าง API Key ที่ Google AI Studio','Create an API key in Google AI Studio')}</a><p>{text('ตั้ง GEMINI_API_KEY เป็น secret ของเว็บฝั่งเซิร์ฟเวอร์ ห้ามใส่ในโค้ดหน้าเว็บ ตั้ง GEMINI_MODEL และ GEMINI_AUDIO_MODEL เพื่อเลือกโมเดลได้ ค่าเริ่มต้น gemini-3.8-flash','Set GEMINI_API_KEY as a server-side Site secret, never in frontend code. GEMINI_MODEL and GEMINI_AUDIO_MODEL select the model; default gemini-3.8-flash.')}</p></div>}
 </div>{message&&<p role="status" className="text-amber-200">{message}</p>}
 </section>;
}
