import test from 'node:test';
import assert from 'node:assert/strict';
import React from 'react';
import {act,create} from 'react-test-renderer';
import {ScoutProvider,useScout} from '../src/stores/ScoutContext';
import {parseSequence} from '../src/domain/localParser';
import {validationErrors} from '../src/domain/validation';
import {calculateBadmintonScore} from '../src/sports/badminton';
import type {ParsedEvent} from '../src/types/scout';

test('Thai spoken aliases and spaced +1 produce canonical scoring evidence',()=>{for(const phrase of ['เอตบเร็วตำแหน่งหน้าขวา + 1 ได้แต้ม','ทีมเอตบเร็วตำแหน่งหน้าขวาบวกหนึ่งได้แต้ม','บีตบจากหน้าขวา +1 ได้แต้ม']){const event=parseSequence(phrase,'badminton')[0];assert.equal(event.actorSide,phrase.startsWith('บี')?'B':'A');assert.equal(event.action,'Smash');assert.equal(event.originZone,'Front Right');assert.equal(event.targetZone,undefined);assert.equal(event.scoreImpact?.points,1);assert.equal(event.scoreImpact?.sideAwarded,event.actorSide);assert.deepEqual(validationErrors(event),[]);}const unknown=parseSequence('ตบเร็วตำแหน่งหน้าขวา + 1 ได้แต้ม','badminton')[0];assert.equal(unknown.actorSide,undefined);assert.ok(validationErrors(unknown).includes('Actor unknown'));assert.equal(parseSequence('เอาบอลมาตบได้แต้ม','badminton')[0].actorSide,undefined);});

test('Real React flow: unknown actor, edit, confirm, scoreboard, edit side, delete',async()=>{(globalThis as any).IS_REACT_ACT_ENVIRONMENT=true;const original=globalThis.fetch;globalThis.fetch=async url=>new Response(JSON.stringify(String(url).endsWith('/health')?{hasApiKey:true,model:'test'}:{success:true,data:{needsReview:true,events:[{action:'Smash',originZone:'Front Right',outcome:'WINNER',scoreImpact:{points:1}}]}}),{headers:{'content-type':'application/json'}});let context!:ReturnType<typeof useScout>;function Harness(){context=useScout();return null;}let renderer:any;try{await act(async()=>{renderer=create(React.createElement(ScoutProvider,null,React.createElement(Harness)));});await act(async()=>{await context.processUtterance('นายกรตบเร็วตำแหน่งหน้าขวา + 1 ได้แต้ม');});const pending=context.currentSession.events[0];assert.equal(context.scoreState.scoreA,0);let failed:any;await act(async()=>{failed=context.updateEvent({...pending,status:'CONFIRMED',needsReview:false});});assert.equal(failed.success,false);assert.equal(context.scoreState.scoreA,0);await act(async()=>{const edited={...pending,actorSide:'A' as const,player:'A' as const,scoreImpact:{points:1,sideAwarded:'A' as const},status:'REVIEW_REQUIRED' as const};assert.equal(context.updateEvent(edited).success,true);});assert.equal(context.scoreState.scoreA,0);await act(async()=>{const edited=context.currentSession.events[0];assert.equal(context.updateEvent({...edited,status:'CONFIRMED',needsReview:false}).success,true);});assert.equal(context.scoreState.scoreA,1);assert.equal(context.currentSession.playerA.score,1);assert.equal(context.currentSession.events[0].status,'CONFIRMED');await act(async()=>{context.updateEvent({...context.currentSession.events[0],actorSide:'B',player:'B',scoreImpact:{points:1,sideAwarded:'B'}});});assert.equal(context.scoreState.scoreA,0);assert.equal(context.scoreState.scoreB,1);await act(async()=>{context.deleteEvent(pending.id);});assert.equal(context.currentSession.playerB.score,0);}finally{if(renderer)await act(async()=>renderer.unmount());globalThis.fetch=original;}});

test('A reviewed point accepted after a correction counts once and replays on delete',()=>{const event={id:'point',sport:'badminton',timestamp:'2026-09-30T10:00:00Z',confirmedAt:'2026-09-30T10:02:00Z',actorSide:'A',action:'Smash',originZone:'Front Right',outcome:'WINNER',scoreImpact:{points:1,sideAwarded:'A'},status:'CONFIRMED',rallyId:'rally',sessionId:'s',source:'voice'} as ParsedEvent;const baseline={...event,id:'baseline',timestamp:'2026-09-30T10:01:00Z',confirmedAt:undefined,recordType:'SCORE_CORRECTION',scoreImpact:{points:0},scoreCorrection:{scoreA:4,scoreB:3,setsA:0,setsB:0,currentSet:1,reason:'Manual baseline'}} as ParsedEvent;assert.equal(calculateBadmintonScore([baseline,event]).scoreA,5);assert.equal(calculateBadmintonScore([baseline]).scoreA,4);assert.equal(calculateBadmintonScore([baseline,{...event,actorSide:'B',scoreImpact:{points:1,sideAwarded:'B'}}]).scoreB,4);});

test('Actor self-correction chooses last explicit Thai or English side',()=>{assert.equal(parseSequence('เอ เอ้ย B ตบได้แต้ม','badminton')[0].actorSide,'B');assert.equal(parseSequence('B เอ้ย เอ ตบได้แต้ม','badminton')[0].actorSide,'A');});

test('Clear user example converts and updates the board without an AI request',async()=>{(globalThis as any).IS_REACT_ACT_ENVIRONMENT=true;let requests=0;const original=globalThis.fetch;globalThis.fetch=async url=>{if(String(url).endsWith('/health'))return new Response('{"hasApiKey":true}');requests++;throw Error('Clear vocabulary must not wait on AI');};let context!:ReturnType<typeof useScout>;function Harness(){context=useScout();return null;}let renderer:any;try{await act(async()=>{renderer=create(React.createElement(ScoutProvider,null,React.createElement(Harness)));});await act(async()=>{await context.processUtterance('เอตบเร็วตำแหน่งหน้าขวา + 1 ได้แต้ม');});assert.equal(requests,0);assert.equal(context.currentSession.playerA.score,1);assert.equal(context.currentSession.events[0].originZone,'Front Right');assert.equal(context.diagnostics.provider,'RULES (no AI request)');}finally{if(renderer)await act(async()=>renderer.unmount());globalThis.fetch=original;}});
test('Fast grammar refuses unknown actors, negatives, ambiguity and multiple actions',async()=>{const {fastVocabularyEvent}=await import('../src/domain/fastVocabulary');for(const text of ['ตบเร็วตำแหน่งหน้าขวา +1 ได้แต้ม','เอตบไม่ได้แต้ม','เอ ตบ เอ้ยไม่ใช่ บีหยอดได้แต้ม','A ตบ B ยก A หยอดได้แต้ม','A ตบหน้าขวาได้แต้ม','ทีมเอ ตบแล้วไม่รู้ว่าใครได้แต้ม'])assert.equal(fastVocabularyEvent(text,'badminton'),null,text);assert.equal(fastVocabularyEvent('เอหยอดได้แต้ม','badminton')?.targetZone,undefined);assert.equal(fastVocabularyEvent('A ผิดพลาดได้แต้ม','volleyball'),null);});

test('Continuous UI receives live tags, confirms once, keeps listening and applies later correction',async()=>{
 const {ContinuousSpeechProvider}=await import('../src/services/speech/ContinuousSpeechProvider');
 const proto=ContinuousSpeechProvider.prototype;const oldStart=proto.start,oldStop=proto.stop,oldCapturing=proto.isCapturing;const oldFetch=globalThis.fetch;let callbacks:any;let capturing=false;
 proto.start=async function(cb){callbacks=cb;capturing=true;cb.onStatus('listening');return true;};proto.stop=async function(){capturing=false;callbacks?.onStatus('stopped');};proto.isCapturing=()=>capturing;
 globalThis.fetch=async()=>new Response('{"hasApiKey":true,"hasDeepgramKey":true}');let context!:ReturnType<typeof useScout>;function Harness(){context=useScout();return null;}let renderer:any;
 try{await act(async()=>{renderer=create(React.createElement(ScoutProvider,null,React.createElement(Harness)));});await act(async()=>context.startListening());assert.equal(context.isRealMicActive,true);
 await act(async()=>callbacks.onTranscript('live-one','เอ ตบจากหน้าขวา',false));assert.ok(context.liveTags.includes('Smash'));assert.equal(context.currentSession.events.length,0);
 await act(async()=>callbacks.onTranscript('live-one','เอ ตบจากหน้าขวาได้แต้ม',true));assert.equal(context.scoreState.scoreA,1);assert.equal(context.isRealMicActive,true);
 await act(async()=>callbacks.onTranscript('live-one','เอ ตบจากหน้าขวาได้แต้ม',true));assert.equal(context.scoreState.scoreA,1);assert.equal(context.currentSession.events.length,1);
 await act(async()=>callbacks.onTranscript('correction','เอ้ย หลังขวา',true));assert.equal(context.currentSession.events.length,1);assert.equal(context.currentSession.events[0].originZone,'Rear Right');assert.equal(context.scoreState.scoreA,1);
 await act(async()=>context.stopListening());assert.equal(context.isRealMicActive,false);
 }finally{if(renderer)await act(async()=>renderer.unmount());proto.start=oldStart;proto.stop=oldStop;proto.isCapturing=oldCapturing;globalThis.fetch=oldFetch;}
});
