import test from 'node:test';import assert from 'node:assert/strict';
import {extractLiveSequence} from '../src/domain/liveGrammar';
import {StreamTranscriptAssembler} from '../src/domain/streamTranscript';
import {sportVocabulary} from '../src/domain/scoutVocabulary';
import {validationErrors} from '../src/domain/validation';
import {handleApi} from '../src/server/api';
import {GeminiServerInterpreter} from '../src/services/interpreter/ScoutInterpreter';
import {calculateBadmintonScore} from '../src/sports/badminton';
const cases:[string,'badminton'|'volleyball',string,string,number][]=[
 ['correct origin','badminton','A อยู่ขวาหน้า เอ้ยไม่ใช่ขวาหลัง แล้วหยอดไปหน้าซ้าย ได้หนึ่ง','Drop',1],
 ['unknown locations','badminton','เอหยอดได้แต้ม','Drop',1],
 ['excited repeated attack','badminton','เอ ตบ ตบ ตบจากหลังขวาไปหน้าซ้าย ได้แต้ม ได้แต้ม บวกหนึ่ง','Smash',1],
 ['actor correction','badminton','เอ เอ้ย บี ตบได้แต้ม','Smash',1],
 ['action correction','badminton','เอ ตบ เอ้ยไม่ใช่ หยอดไปหน้าซ้ายได้แต้ม','Drop',1],
 ['reception correction','volleyball','บี รับสาม เอ้ย รับสอง','Reception',0],
 ['blocked attack','volleyball','เอ ตบติดบล็อก','Attack',1],
 ['serve ace','volleyball','ทีมเอ เบอร์ 7 เสิร์ฟจัมพ์โฟลตไปโซน 5 ได้เอซ','Serve',1],
 ['cover','volleyball','ทีมบี รองบล็อก','Cover',0],
 ['free ball','volleyball','บี ส่งฟรีบอลไปโซน 1','Free Ball',0],
 ['long set','volleyball','บี เซ็ตบอลเร็วกลาง','Set',0],
];
for(const [label,sport,text,action,points]of cases)test('Excited voice simulation: '+label,()=>{const result=extractLiveSequence(text,sport);assert.equal(result.needsReview,false,JSON.stringify(result));assert.equal(result.events.length,1);assert.equal(result.events[0].action,action);assert.equal(result.events[0].scoreImpact?.points,points);assert.deepEqual(validationErrors(result.events[0]),[]);});
test('Corrections update only known evidence',()=>{const e=extractLiveSequence(cases[0][2],'badminton').events[0];assert.equal(e.originZone,'Rear Right');assert.equal(e.targetZone,'Front Left');assert.equal(extractLiveSequence('เอ เอ้ย บี ตบได้แต้ม','badminton').events[0].actorSide,'B');assert.equal(extractLiveSequence('บี รับสาม เอ้ย รับสอง','volleyball').events[0].receptionQuality,2);});
test('Dictionary aliases across both sports map to legal actions without network',()=>{for(const sport of ['badminton','volleyball']as const)for(const[action,words]of Object.entries(sportVocabulary[sport]))for(const word of words){const result=extractLiveSequence(`ทีมเอ ${word}`,sport);assert.equal(result.events[0]?.action,action,`${sport}: ${word}`);assert.equal(result.events.length,1,`${sport}: ${word}`);}});
test('Volleyball sequential rally never copies jersey or zone into another contact',()=>{const r=extractLiveSequence('ทีม A เบอร์ 7 เสิร์ฟไปโซน 5 B รับสาม เซ็ตบอลเร็วกลาง เบอร์ 10 ตบลง ได้แต้ม','volleyball');assert.equal(r.needsReview,false);assert.deepEqual(r.events.map(e=>e.action),['Serve','Reception','Set','Attack']);assert.deepEqual(r.events.map(e=>e.actorSide),['A','B','B','B']);assert.deepEqual(r.events.map(e=>e.actorPlayer?.jerseyNumber),['7',undefined,undefined,'10']);assert.equal(r.events[0].targetZone,'Zone 5');assert.equal(r.events[1].receptionQuality,3);assert.equal(r.events[1].originZone,undefined);assert.equal(r.events.reduce((s,e)=>s+e.scoreImpact!.points,0),1);});
test('Unknown, speculative, illegal and irrelevant speech never auto-confirms',()=>{for(const [sport,text] of [['badminton','หยอดได้แต้ม'],['badminton','เอ ตบไม่ได้แต้ม'],['badminton','เอ ตบน่าจะได้แต้ม'],['badminton','เอ ตบจากดาวอังคารได้แต้ม'],['badminton','เอ หยอดวันนี้อาหารอร่อยได้แต้ม'],['volleyball','บี รับเก้า'],['volleyball','บี รับ 99'],['volleyball','เอ เสิร์ฟไปโซน 9'],['volleyball','เอ ตบหน้าขวาได้แต้ม'],['volleyball','เอ เสิร์ฟได้แต้ม บี ตบได้แต้ม']]as const)assert.equal(extractLiveSequence(text,sport).needsReview,true,text);});
const packet=(text:string,start:number,is_final=false,speech_final=false)=>({type:'Results',start,duration:1,is_final,speech_final,channel:{alternatives:[{transcript:text}]}});
test('Interim replacements stay provisional and duplicate final packets cannot score twice',()=>{const a=new StreamTranscriptAssembler();const one=a.accept(packet('เอ ตบหน้าขวา',0));const two=a.accept(packet('เอ ตบจากหลังขวา',0));assert.equal(one?.id,two?.id);assert.equal(two?.text,'เอ ตบจากหลังขวา');assert.equal(two?.final,false);a.accept(packet('เอ ตบจากหลังขวา',0,true));const final=a.accept(packet('ได้แต้ม',1,true,true));assert.equal(final?.text,'เอ ตบจากหลังขวา ได้แต้ม');assert.equal(final?.final,true);assert.equal(a.accept(packet('ได้แต้ม',1,true,true)),null);});
test('Utterance end or stop cannot confirm a provider interim fragment',()=>{const a=new StreamTranscriptAssembler();a.accept(packet('เอได้แต้ม',0));assert.equal(a.flush(),null);a.accept(packet('เอ ตบ',1,true));a.accept(packet('ได้แต้ม',2));assert.equal(a.accept({type:'UtteranceEnd'})?.text,'เอ ตบ');});
test('A full sequence uses one rally, only one scoring endpoint and no AI call',async()=>{const old=globalThis.fetch;globalThis.fetch=async()=>{throw Error('Network must not be used');};try{const score=calculateBadmintonScore([]);const r=await new GeminiServerInterpreter().interpret('A ตบจากหลังขวา B ยกกลับ แล้ว A หยอดหน้าซ้ายได้แต้ม',{sport:'badminton',playerAName:'Player A',playerBName:'Player B',scoreA:0,scoreB:0,currentSet:1,scoreState:score,recentEvents:[]});assert.equal(new Set(r.events.map(e=>e.rallyId)).size,1);assert.equal(r.events.length,3);assert.equal(r.needsReview,false);assert.equal(calculateBadmintonScore(r.events).scoreA,1);}finally{globalThis.fetch=old;}});
test('Deepgram token route fails honestly without a separate key',async()=>{const r=await handleApi(new Request('https://test.example/api/deepgram-token',{method:'POST',body:'{}'}),{GEMINI_API_KEY:'gemini-test'});assert.equal(r.status,503);assert.equal((await r.json()).code,'DEEPGRAM_NOT_CONFIGURED');});
test('Deepgram sends server key only to grant endpoint and returns only temporary token',async()=>{const old=globalThis.fetch;globalThis.fetch=async(url,opts)=>{assert.equal(String(url),'https://api.deepgram.com/v1/auth/grant');assert.equal(new Headers(opts?.headers).get('Authorization'),'Token deepgram-test-key-more-than-20');return new Response('{"access_token":"temporary-test-token","expires_in":30}');};try{const r=await handleApi(new Request('https://test.example/api/deepgram-token',{method:'POST',body:'{}'}),{DEEPGRAM_API_KEY:'deepgram-test-key-more-than-20'});assert.equal(r.status,200);const text=await r.text();assert.ok(!text.includes('deepgram-test-key'));assert.equal(JSON.parse(text).token,'temporary-test-token');}finally{globalThis.fetch=old;}});
test('Split volleyball contacts retain team only for safe within-team transitions',()=>{assert.equal(extractLiveSequence('เซ็ตเร็ว','volleyball','','',{side:'B',action:'Reception'}).events[0].actorSide,'B');assert.equal(extractLiveSequence('เบอร์ 10 ตบได้แต้ม','volleyball','','',{side:'B',action:'Set'}).events[0].actorSide,'B');assert.equal(extractLiveSequence('รับสาม','volleyball','','',{side:'A',action:'Serve'}).needsReview,true);assert.equal(extractLiveSequence('เสิร์ฟ','volleyball','','',{side:'B',action:'Attack'}).needsReview,true);});
test('A correction after a streaming pause edits evidence rather than awarding again',async()=>{const {extractLiveCorrection}=await import('../src/domain/liveGrammar');const original={...extractLiveSequence('เอ ตบจากหน้าขวาได้แต้ม','badminton').events[0],id:'existing',timestamp:new Date().toISOString(),sessionId:'s',source:'voice',status:'CONFIRMED'}as any;const fixed=extractLiveCorrection('เอ้ย หลังขวา',original)!;assert.equal(fixed.id,'existing');assert.equal(fixed.originZone,'Rear Right');assert.equal(fixed.scoreImpact.points,1);const actor=extractLiveCorrection('เอ้ย บี',fixed)!;assert.equal(actor.scoreImpact.sideAwarded,'B');const noPoint=extractLiveCorrection('เอ้ย ไม่ได้แต้ม',actor)!;assert.equal(noPoint.scoreImpact.points,0);assert.equal(extractLiveCorrection('เอ้ย โซน 9',original),null);assert.equal(extractLiveCorrection('เอ้ย น่าจะหลังขวา',original),null);});
test('Continuous microphone transport batches real PCM, delivers replaceable text, and releases devices on stop',async()=>{
 const {ContinuousSpeechProvider}=await import('../src/services/speech/ContinuousSpeechProvider');const names=['navigator','window','AudioWorkletNode','WebSocket'];const old=new Map(names.map(n=>[n,Object.getOwnPropertyDescriptor(globalThis,n)]));const oldFetch=globalThis.fetch;let released=false,closed=false;let node:any,socket:any;const sent:any[]=[],updates:any[]=[];
 class Node{port={onmessage:null as any};constructor(){node=this;}connect(){return {connect(){}};}disconnect(){}}
 class Context{sampleRate=48000;state='running';destination={};audioWorklet={addModule:async(path:string)=>assert.equal(path,'/scout-pcm-worklet.js')};async resume(){}createMediaStreamSource(){return {connect(){}};}createGain(){return {gain:{value:1}};}async close(){closed=true;this.state='closed';}}
 class Socket{static OPEN=1;readyState=0;bufferedAmount=0;onopen:any;onerror:any;onclose:any;onmessage:any;constructor(url:string,protocols:string[]){socket=this;assert.ok(url.includes('language=th'));assert.ok(url.includes('sample_rate=48000'));assert.deepEqual(protocols,['bearer','temporary-token']);setTimeout(()=>{this.readyState=1;this.onopen?.();},0);}send(data:any){sent.push(data);}close(){this.readyState=3;this.onclose?.();}}
 for(const [name,value]of Object.entries({navigator:{mediaDevices:{getUserMedia:async()=>({getTracks:()=>[{stop(){released=true;},onended:null}]})}},window:{AudioContext:Context},AudioWorkletNode:Node,WebSocket:Socket}))Object.defineProperty(globalThis,name,{configurable:true,value});globalThis.fetch=async()=>new Response('{"success":true,"token":"temporary-token"}');
 try{const provider=new ContinuousSpeechProvider();assert.equal(await provider.start({onTranscript:(...args)=>updates.push(args),onLevel:()=>{},onStatus:()=>{},onError:message=>{throw Error(message);}},{language:'th',sport:'volleyball',provider:'deepgram'}),true);const actual=new Int16Array([100,-100,55]);node.port.onmessage({data:{pcm:actual.buffer,level:0.1}});assert.equal(sent[0],actual.buffer);socket.onmessage({data:JSON.stringify(packet('ทีมเอเสิร์ฟ',0))});socket.onmessage({data:JSON.stringify(packet('ทีมเอเสิร์ฟได้เอซ',0,true,true))});assert.equal(updates[0][2],false);assert.equal(updates[1][2],true);assert.equal(provider.isCapturing(),true);await provider.stop();assert.equal(provider.isCapturing(),false);assert.equal(released,true);assert.equal(closed,true);assert.ok(sent.some(data=>typeof data==='string'&&data.includes('Finalize')));assert.ok(sent.some(data=>typeof data==='string'&&data.includes('CloseStream')));
 }finally{globalThis.fetch=oldFetch;for(const[name,descriptor]of old){if(descriptor)Object.defineProperty(globalThis,name,descriptor);else delete(globalThis as any)[name];}}
});
test('Spoken jersey numbers preserve tens and cannot silently become a different athlete',()=>{for(const[word,n]of [['สิบสอง','12'],['ยี่สิบสาม','23'],['สามสิบสอง','32'],['หนึ่งศูนย์','10']]as const){const result=extractLiveSequence(`ทีมเอ เบอร์${word} ตบได้แต้ม`,'volleyball');assert.equal(result.needsReview,false,word);assert.equal(result.events[0].actorPlayer?.jerseyNumber,n);}assert.equal(extractLiveSequence('บี รับสิบสอง','volleyball').needsReview,true);assert.equal(extractLiveSequence('ทีมเอ เสิร์ฟไปโซนเก้า','volleyball').needsReview,true);});
test('Unexplained numeric data cannot disappear into a plausible confirmed event',()=>{for(const text of ['เอ ตบ 999 ได้แต้ม','เอ ตบ +2 ได้แต้ม','เอ ตบสองสามได้แต้ม'])assert.equal(extractLiveSequence(text,'badminton').needsReview,true,text);});
test('An unnamed opponent is never inferred from serve or free-ball transitions',()=>{assert.equal(extractLiveSequence('เอ เสิร์ฟไปโซน 5 รับสาม','volleyball').needsReview,true);assert.equal(extractLiveSequence('เอ ฟรีบอล ขุด','volleyball').needsReview,true);});
