import test from 'node:test';
import assert from 'node:assert/strict';
import {handleApi} from '../src/server/api';
import {SpeechCaptureProvider} from '../src/services/speech/SpeechProvider';
import {translate} from '../src/i18n/LocaleContext';
const request=(path:string,body:unknown)=>new Request('https://test.example/api/'+path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});
test('Thai UI translates labels without changing canonical sport values',()=>{assert.equal(translate('App Settings','th'),'ตั้งค่าแอป');assert.equal(translate('App Settings','en'),'App Settings');});
test('Unconfigured server reports state and refuses cloud transcription',async()=>{const health=await (await handleApi(new Request('https://test.example/api/health'),{})).json();assert.equal(health.hasApiKey,false);const res=await handleApi(request('transcribe',{audio:'a'.repeat(20),mimeType:'audio/webm'}),{});assert.equal(res.status,503);assert.equal((await res.json()).code,'API_NOT_CONFIGURED');});
test('Recorded audio goes to provider and transcript is preserved',async()=>{const original=globalThis.fetch;let received:any;globalThis.fetch=async(_url,options)=>{received=JSON.parse(options!.body as string);assert.equal(new Headers(options!.headers).get('x-goog-api-key'),'test-only-key');return new Response(JSON.stringify({candidates:[{content:{parts:[{text:JSON.stringify({transcript:'A หยอดได้แต้ม'})}]}}]}));};try{const res=await handleApi(request('transcribe',{audio:'a'.repeat(20),mimeType:'audio/webm',language:'th'}),{GEMINI_API_KEY:'test-only-key'});assert.equal((await res.json()).transcript,'A หยอดได้แต้ม');assert.equal(received.contents[0].parts[0].inlineData.mimeType,'audio/webm');}finally{globalThis.fetch=original;}});
test('No-key summary is labelled recorded statistics',async()=>{const result=await (await handleApi(request('coach-summary',{sport:'badminton',metrics:{confirmedEvents:4,totalRallies:2}}),{})).json();assert.equal(result.provider,'LOCAL_METRICS');assert.equal(result.data.turningPoints.length,0);});
test('Speech stop waits for final result delivered asynchronously',async()=>{const descriptors=new Map<string,PropertyDescriptor|undefined>();const replace=(key:string,value:any)=>{descriptors.set(key,Object.getOwnPropertyDescriptor(globalThis,key));Object.defineProperty(globalThis,key,{configurable:true,writable:true,value});};let stopped=false;class Recognition{onresult:any;onend:any;onerror:any;start(){}stop(){setTimeout(()=>{this.onresult?.({resultIndex:0,results:[Object.assign([{transcript:'A หยอดได้แต้ม'}],{isFinal:true})]});this.onend?.();},15);}abort(){}}replace('navigator',{mediaDevices:{getUserMedia:async()=>({getTracks:()=>[{stop(){stopped=true;}}]})}});replace('window',{SpeechRecognition:Recognition});replace('MediaRecorder',undefined);try{const provider=new SpeechCaptureProvider();assert.equal(await provider.start({}),true);const result=await provider.stop();assert.equal(result.finalTranscript,'A หยอดได้แต้ม');assert.equal(stopped,true);}finally{for(const [key,desc] of descriptors){if(desc)Object.defineProperty(globalThis,key,desc);else delete (globalThis as any)[key];}}});
test('Cancelling permission startup closes a late microphone stream',async()=>{const oldNav=Object.getOwnPropertyDescriptor(globalThis,'navigator');let resolve:any;let closed=false;Object.defineProperty(globalThis,'navigator',{configurable:true,value:{mediaDevices:{getUserMedia:()=>new Promise(r=>resolve=r)}}});try{const provider=new SpeechCaptureProvider();const start=provider.start({});assert.equal((await provider.stop()).finalTranscript,'');resolve({getTracks:()=>[{stop(){closed=true;}}]});assert.equal(await start,false);assert.equal(closed,true);}finally{if(oldNav)Object.defineProperty(globalThis,'navigator',oldNav);else delete (globalThis as any).navigator;}});

test('Only owner can change provider key, and invalid provider response never saves it',async()=>{const unauthorized=await handleApi(request('provider-key',{apiKey:'test-key-with-more-than-twenty-characters'}),{SETTINGS_OWNER_EMAIL:'owner@example.com'});assert.equal(unauthorized.status,403);let written=false;const env={SETTINGS_OWNER_EMAIL:'owner@example.com',KEY_ENCRYPTION_SECRET:Buffer.alloc(32).toString('base64'),DB:{prepare:()=>({bind:()=>({first:async()=>null,run:async()=>{written=true;}}),first:async()=>null})}};const original=globalThis.fetch;globalThis.fetch=async()=>new Response(JSON.stringify({error:{message:'invalid'}}),{status:403});try{const req=request('provider-key',{apiKey:'test-key-with-more-than-twenty-characters'});req.headers.set('oai-authenticated-user-email','owner@example.com');const res=await handleApi(req,env);assert.equal(res.status,502);assert.equal(written,false);assert.ok(!(await res.text()).includes('test-key'));}finally{globalThis.fetch=original;}});
test('Owner key is verified, encrypted, persists and never returned',async()=>{let stored='';const env={SETTINGS_OWNER_EMAIL:'owner@example.com',KEY_ENCRYPTION_SECRET:Buffer.alloc(32,9).toString('base64'),DB:{prepare:(sql:string)=>({bind:(...values:string[])=>({first:async()=>stored?{ciphertext:stored}:null,run:async()=>{stored=values[1];}}),first:async()=>null})}};const original=globalThis.fetch;globalThis.fetch=async()=>new Response(JSON.stringify({candidates:[{content:{parts:[{text:'{"ok":true}'}]}}]}));try{const req=request('provider-key',{apiKey:'test-key-with-more-than-twenty-characters'});req.headers.set('oai-authenticated-user-email','owner@example.com');const res=await handleApi(req,env);assert.equal(res.status,200);assert.ok(!stored.includes('test-key'));assert.ok(!(await res.text()).includes('test-key'));const {readProviderKey}=await import('../src/server/keyStore');assert.equal(await readProviderKey(env),'test-key-with-more-than-twenty-characters');const health=await handleApi(new Request('https://test.example/api/health'),env);assert.equal((await health.json()).hasApiKey,true);}finally{globalThis.fetch=original;}});

test('Transient Gemini overload retries and recovers instead of blaming the key',async()=>{let calls=0;const original=globalThis.fetch;globalThis.fetch=async()=>{calls++;return calls===1?new Response(JSON.stringify({error:{status:'UNAVAILABLE',message:'High demand'}}),{status:503}):new Response(JSON.stringify({candidates:[{content:{parts:[{text:'{"ok":true}'}]}}]}));};try{const res=await handleApi(request('verify-provider',{}),{GEMINI_API_KEY:'test-only-key'});assert.equal(res.status,200);assert.equal(calls,2);}finally{globalThis.fetch=original;}});
test('Authentication failures do not retry and provider error redacts key',async()=>{let calls=0;const original=globalThis.fetch;globalThis.fetch=async()=>{calls++;return new Response(JSON.stringify({error:{status:'UNAUTHENTICATED',message:'Bad test-only-key'}}),{status:401});};try{const res=await handleApi(request('verify-provider',{}),{GEMINI_API_KEY:'test-only-key'});const result=await res.json();assert.equal(result.code,'API_KEY_INVALID');assert.ok(result.error.includes('HTTP 401'));assert.ok(!result.error.includes('test-only-key'));assert.equal(calls,1);}finally{globalThis.fetch=original;}});

test('Digital silence is not sent to AI or turned into invented speech',async()=>{const wav=Buffer.alloc(32044);wav.write('RIFF',0);wav.writeUInt32LE(32036,4);wav.write('WAVE',8);wav.write('fmt ',12);wav.writeUInt32LE(16,16);wav.writeUInt16LE(1,20);wav.writeUInt16LE(1,22);wav.writeUInt32LE(16000,24);wav.writeUInt32LE(32000,28);wav.writeUInt16LE(2,32);wav.writeUInt16LE(16,34);wav.write('data',36);wav.writeUInt32LE(32000,40);let calls=0;const original=globalThis.fetch;globalThis.fetch=async()=>{calls++;throw Error('Must not call AI');};try{const res=await handleApi(request('transcribe',{audio:wav.toString('base64'),mimeType:'audio/wav',language:'th'}),{GEMINI_API_KEY:'test-key'});const data=await res.json();assert.equal(data.transcript,'');assert.equal(data.skipped,'SILENT_AUDIO');assert.equal(calls,0);const {isSilentPcmWav}=await import('../src/server/silentAudio');wav.writeInt16LE(123,44);assert.equal(isSilentPcmWav(wav.toString('base64')),false);}finally{globalThis.fetch=original;}});

test('Overloaded primary model falls back to configured model',async()=>{const urls:string[]=[];const original=globalThis.fetch;globalThis.fetch=async url=>{urls.push(String(url));return urls.length===1?new Response(JSON.stringify({error:{status:'UNAVAILABLE'}}),{status:503}):new Response(JSON.stringify({candidates:[{content:{parts:[{text:'{"transcript":"A หยอดได้แต้ม"}'}]}}]}));};try{const res=await handleApi(request('transcribe',{audio:'a'.repeat(20),mimeType:'audio/webm'}),{GEMINI_API_KEY:'test-key',GEMINI_AUDIO_MODEL:'primary',GEMINI_AUDIO_FALLBACK_MODEL:'backup'});const result=await res.json();assert.equal(result.model,'backup');assert.ok(urls[0].includes('/primary:'));assert.ok(urls[1].includes('/backup:'));}finally{globalThis.fetch=original;}});
test('Failed cloud transcription retains recorded bytes for retry',async()=>{const keys=['navigator','window','MediaRecorder'];const previous=new Map(keys.map(k=>[k,Object.getOwnPropertyDescriptor(globalThis,k)]));const original=globalThis.fetch;class Recorder{static isTypeSupported(){return true;}state='inactive';mimeType='audio/webm';ondataavailable:any;onstop:any;onerror:any;start(){this.state='recording';}stop(){this.state='inactive';this.ondataavailable({data:new Blob(['recorded-test-bytes'])});this.onstop();}}Object.defineProperty(globalThis,'navigator',{configurable:true,value:{mediaDevices:{getUserMedia:async()=>({getTracks:()=>[{stop(){}}]})}}});Object.defineProperty(globalThis,'window',{configurable:true,value:{}});Object.defineProperty(globalThis,'MediaRecorder',{configurable:true,value:Recorder});globalThis.fetch=async()=>new Response(JSON.stringify({success:false,error:'Provider overloaded'}),{status:503});try{const provider=new SpeechCaptureProvider();provider.configure({serverAvailable:true});assert.equal(await provider.start({}),true);const {FailedRecording}=await import('../src/services/speech/SpeechProvider');const failed=await provider.stop().then(()=>null,error=>error);assert.ok(failed instanceof FailedRecording);assert.equal(await failed.audio.text(),'recorded-test-bytes');}finally{globalThis.fetch=original;for(const [key,desc] of previous){if(desc)Object.defineProperty(globalThis,key,desc);else delete (globalThis as any)[key];}}});

test('Automatic mode uses a real final browser transcript without uploading audio',async()=>{const names=['navigator','window','MediaRecorder'];const old=new Map(names.map(key=>[key,Object.getOwnPropertyDescriptor(globalThis,key)]));const original=globalThis.fetch;let requests=0;class Recorder{static isTypeSupported(){return true;}state='inactive';mimeType='audio/webm';ondataavailable:any;onstop:any;start(){this.state='recording';}stop(){this.state='inactive';this.ondataavailable({data:new Blob(['real-captured-audio-placeholder-in-test'])});this.onstop();}}class Recognition{onresult:any;onend:any;start(){}stop(){this.onresult?.({resultIndex:0,results:[Object.assign([{transcript:'เอตบเร็วตำแหน่งหน้าขวา +1 ได้แต้ม'}],{isFinal:true})]});this.onend?.();}abort(){}}Object.defineProperty(globalThis,'navigator',{configurable:true,value:{mediaDevices:{getUserMedia:async()=>({getTracks:()=>[{stop(){}}]})}}});Object.defineProperty(globalThis,'window',{configurable:true,value:{SpeechRecognition:Recognition}});Object.defineProperty(globalThis,'MediaRecorder',{configurable:true,value:Recorder});globalThis.fetch=async()=>{requests++;throw Error('Audio upload should be skipped');};try{const provider=new SpeechCaptureProvider();provider.configure({serverAvailable:true,mode:'auto'});assert.equal(await provider.start({}),true);const result=await provider.stop();assert.equal(result.finalTranscript,'เอตบเร็วตำแหน่งหน้าขวา +1 ได้แต้ม');assert.equal(requests,0);assert.ok(result.provider.includes('Browser'));}finally{globalThis.fetch=original;for(const [key,desc] of old){if(desc)Object.defineProperty(globalThis,key,desc);else delete (globalThis as any)[key];}}});
