import {SportType,Side} from './types';
export const actorAliases={A:['A','เอ','ทีมเอ','ทีม เอ','ทีม A','ฝั่งเอ','ฝั่ง เอ','ฝั่ง A'],B:['B','บี','ทีมบี','ทีม บี','ทีม B','ฝั่งบี','ฝั่ง บี','ฝั่ง B']};
// Synonyms name observations; tactical variants stay subtypes, never extra legal actions.
export const sportVocabulary={
 badminton:{Serve:['เสิร์ฟ','เสิรฟ','เสิฟ','เสิร์ฟสั้น','เสิร์ฟยาว','เสิร์ฟสูง','เสิร์ฟสะบัด','เสิร์ฟแบ็กแฮนด์'],Return:['รับเสิร์ฟ','รีเทิร์น','รับลูกเสิร์ฟ'],Clear:['เคลียร์','เคลีย','ตีโด่ง','ตีลูกโด่ง','ตีไปท้ายคอร์ต'],Drop:['หยอด','ดรอป','ดร็อป','ตัดหยอด','หยอดเร็ว','หยอดช้า'],Smash:['ตบ','สแมช','สแมชช์','ตบเร็ว','ตบหนัก','กระโดดตบ','ตบเฉียง','ตบตรง'],Drive:['ไดรฟ์','ไดร์ฟ','ดาด','ตีดาด'],Lift:['ยก','งัด','ยกลูก','ยกกลับ','งัดขึ้น'], 'Net Shot':['วางหน้าเน็ต','เล่นหน้าเน็ต','ลูกหน้าเน็ต','ปั่นหน้าเน็ต'],'Net Kill':['เน็ตกิล','เน็ตคิล','ซ้ำหน้าเน็ต','ตบหน้าเน็ต','ฆ่าหน้าเน็ต'],Block:['บล็อก','บล็อค','บล็อคตบ','กันตบ']},
 volleyball:{Serve:['เสิร์ฟ','เสิรฟ','เสิฟ','เสิร์ฟลอย','เสิร์ฟโฟลต','เสิร์ฟจัมพ์โฟลต','กระโดดเสิร์ฟ','เสิร์ฟท็อปสปิน','เสิร์ฟสั้น','เสิร์ฟยาว'],Reception:['รับบอลแรก','รับเสิร์ฟ','รับลูกเสิร์ฟ','บอลแรก','รีเซฟ','รีเซฟชั่น','รับ'],Set:['เซ็ต','เซต','เซ็ท','ตั้งบอล','จ่ายบอล','เซ็ตบอลเร็วกลาง','เซ็ตเร็ว','เซ็ตสูง','เซ็ตหัวเสา','เซ็ตกลับหลัง','แบ็กเซ็ต','เซ็ตบอลสอง'],Attack:['ตบ','ตบเร็ว','ตบลง','สไปค์','สปाइक','ตีบอลเร็ว','บอลเร็ว','บอลสั้น','บอลบี','บอลไหล','ตบหัวเสา','ตบสามเมตร','ตบหลัง','หยอด','ทิป','แตะหยอด','ตีทัช','ตบอัดบล็อก'],Block:['บล็อก','บล็อค','สกัด','บล็อกเดี่ยว','บล็อกคู่','บล็อกสามคน','บล็อกแต้ม'],Dig:['ขุด','ดิก','รับตบ','รับลูกตบ','พุ่งรับ','เซฟบอล','รับเกมรับ'], 'Free Ball':['ฟรีบอล','ส่งฟรีบอล','ส่งบอลข้าม'],Cover:['คัฟเวอร์','คัฟเว่อร์','คัฟเวอ','รองบอล','รองบล็อก','รองตบ'],Overpass:['บอลล้น','รับล้น','บอลแรกข้าม','รับข้ามเน็ต'],Error:['ผิดพลาด','ทำเสีย','ฟาวล์','ผิดตำแหน่ง','สัมผัสเน็ต','เหยียบเส้น','บอลสี่จังหวะ','จับบอล','เล่นสองครั้ง']}
};
export const vocabularyCategories={
 actors:actorAliases,
 identity:{jersey:['เบอร์','หมายเลข','#','number'],roles:['ตัวเซ็ต','เซ็ตเตอร์','ลิเบอโร','หัวเสา','บอลเร็ว','บีหลัง','ตัวรับอิสระ']},
 spatial:{origin:['จาก','อยู่','ยืน','ตำแหน่ง','ที่'],target:['ไป','ลง','เป้าหมาย','ตก','to'],badminton:{'Front Left':['หน้าซ้าย','ซ้ายหน้า','หน้า ซ้าย'],'Front Center':['หน้ากลาง','กลางหน้า'],'Front Right':['หน้าขวา','ขวาหน้า','หน้า ขวา'],'Mid Left':['กลางซ้าย','ซ้ายกลาง'],'Mid Center':['กลางสนาม','กลางคอร์ด','กลางคอร์ต','กลางกลาง'],'Mid Right':['กลางขวา','ขวากลาง'],'Rear Left':['หลังซ้าย','ซ้ายหลัง','หลัง ซ้าย'],'Rear Center':['หลังกลาง','กลางหลัง'],'Rear Right':['หลังขวา','ขวาหลัง','หลัง ขวา']},volleyball:['โซน 1','โซน 2','โซน 3','โซน 4','โซน 5','โซน 6']},
 reception:{0:['รับศูนย์','รับ 0','เกรดศูนย์','คุณภาพศูนย์'],1:['รับหนึ่ง','รับ 1','เกรดหนึ่ง','คุณภาพหนึ่ง'],2:['รับสอง','รับ 2','เกรดสอง','คุณภาพสอง'],3:['รับสาม','รับ 3','เกรดสาม','คุณภาพสาม']},
 outcome:{point:['ได้แต้ม','ได้หนึ่ง','ได้หนึ่งแต้ม','บวกหนึ่ง','บวก 1','+1','+ 1','เป็นแต้ม','winner'],ace:['เอซ','ได้เอซ','ace'],kill:['คิล','kill'],error:['เสียแต้ม','เสียเอง','ติดเน็ต','ออก','ตีออก','เสิร์ฟเสีย','เสิร์ฟออก'],blocked:['ติดบล็อก','โดนบล็อก','ถูกบล็อก']},
 correction:['เอ้ย','เอ๊ย','เฮ้ยไม่ใช่','ไม่ใช่','แก้เป็น','เปลี่ยนเป็น','ขอแก้','หมายถึง'],
 hesitation:['เอ่อ','อ่า','อืม','คือ','นะ','ครับ','ค่ะ','เลย','โอ้','โอ้โห'],
 sequence:['แล้ว','จากนั้น','ต่อด้วย','ต่อไป','แรลลี่ใหม่','เริ่มแรลลี่','จบแรลลี่'],
 subtypes:{badminton:['โฟร์แฮนด์','แบ็กแฮนด์','ตรง','เฉียง','ครอส','สั้น','ยาว','สูง','เร็ว','ช้า'],volleyball:['จัมพ์โฟลต','โฟลต','ท็อปสปิน','อันเดอร์แฮนด์','บอลเร็วกลาง','บอลบี','บอลไหล','บอลสูง','หัวเสา','บีหลัง','สามเมตร','ตรง','เฉียง','ตีทัช','หยอด','บล็อกเดี่ยว','บล็อกคู่']}
};
export function canonicalSide(value:unknown):Side|undefined{if(typeof value!=='string')return;return (Object.keys(actorAliases) as Side[]).find(side=>actorAliases[side].some(alias=>alias.toLowerCase()===value.trim().toLowerCase()));}
export function vocabularyPrompt(sport:SportType){return `Sports scouting vocabulary (use only ${sport}): ${JSON.stringify(sportVocabulary[sport])}. Categorized context ${JSON.stringify(vocabularyCategories)}. These are accepted aliases, not default actors. Preserve original speech. Unknown actors remain null. Latest explicit self correction wins: correct only the mentioned field; action corrections replace an action, not a new contact. Repeated excited words do not create extra touches unless a new actor, sequence marker or distinct contact is explicit. Player names resolve only through session names. Origin words describe ORIGIN, target words describe TARGET. Bare placement is ambiguous except explicit Drop placement; missing endpoints remain unknown. Tactical roles and subtypes are not zones and not a basis to invent players. In volleyball, "รับสาม" means Reception quality 3, NOT Zone 3. Numbers after เบอร์ are jerseys, after โซน are zones. Quick attack is Attack, not Set. "เซ็ตบอลเร็วกลาง" is one Set. A winning explicit +1/ได้แต้ม repeated means ONE point per rally; never one point per synonym. ERROR/BLOCKED awards opponent. Unknown winning side requires review. Speech may repeat, hesitate, correct and contain several contacts. Match pauses do not end a rally. Do not infer a winner from power, speed, cheers, ball landing or receipt quality alone. Never promote nonsense or unrelated conversation to confirmed data.`;}
export function speechKeyterms(sport:SportType){return [...new Set(Object.values(sportVocabulary[sport]).map(v=>v[0]).concat(['ทีมเอ','ทีมบี','ได้แต้ม','เบอร์','โซน']))].slice(0,20);}
